[package]
name = "brush-c"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[lib]
name = "brush_c"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
burn-cubecl.workspace = true
brush-process = { path = "../../crates/brush-process", default-features = false }
brush-render = { path = "../../crates/brush-render" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["io-util", "rt", "rt-multi-thread"] }
tokio-stream.workspace = true

[dev-dependencies]
brush-serde = { path = "../../crates/brush-serde" }
tempfile = "3.23.0"

[lints]
workspace = true
